# Generated by Django 4.1 on 2022-08-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('admission_id', models.CharField(max_length=8)),
                ('grade', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('profile', models.ImageField(blank=True, default='profiles/default_user.png', upload_to='media/profiles/')),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Web_Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skil_exp', models.CharField(blank=True, max_length=1000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Videographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dslr_mirrorless_videographer', models.BooleanField(default=False)),
                ('is_arial_videographer', models.BooleanField(default=False)),
                ('is_mobile_videographer', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_premire', models.BooleanField(default=False)),
                ('exp_after', models.BooleanField(default=False)),
                ('exp_filmora', models.BooleanField(default=False)),
                ('other_softwares', models.CharField(blank=True, max_length=200)),
                ('skil_exp', models.CharField(blank=True, max_length=3000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skil_exp', models.CharField(blank=True, max_length=2000)),
                ('course', models.CharField(blank=True, max_length=300)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skil_exp', models.CharField(max_length=2000)),
                ('sinhala_lan', models.BooleanField(default=False)),
                ('english_lan', models.BooleanField(default=False)),
                ('tamil_lan', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dslr_mirrorless_photographer', models.BooleanField(default=False)),
                ('is_arial_photographer', models.BooleanField(default=False)),
                ('is_mobile_photographer', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_lumina', models.BooleanField(default=False)),
                ('exp_photoshop', models.BooleanField(default=False)),
                ('exp_illustrator', models.BooleanField(default=False)),
                ('exp_bridge', models.BooleanField(default=False)),
                ('other_softwares', models.CharField(blank=True, max_length=200)),
                ('skil_exp', models.CharField(blank=True, max_length=3000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_phone', models.CharField(max_length=12)),
                ('parent_adress', models.CharField(max_length=500)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_device', models.CharField(blank=True, max_length=100)),
                ('skil_exp', models.CharField(blank=True, max_length=1000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Graphic_Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_photoshop', models.BooleanField(default=False)),
                ('exp_illustrator', models.BooleanField(default=False)),
                ('exp_coreldraw', models.BooleanField(default=False)),
                ('skil_exp', models.CharField(blank=True, max_length=3000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoghaphy', models.BooleanField(default=False)),
                ('videography', models.BooleanField(default=False)),
                ('technical', models.BooleanField(default=False)),
                ('announcing', models.BooleanField(default=False)),
                ('reporting', models.BooleanField(default=False)),
                ('photo_editing', models.BooleanField(default=False)),
                ('video_editing', models.BooleanField(default=False)),
                ('graphic_design', models.BooleanField(default=False)),
                ('web_design', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
            options={
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.CreateModel(
            name='DSLR_MirrorLess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_cam', models.CharField(blank=True, max_length=100)),
                ('type_of_lense', models.CharField(blank=True, max_length=100)),
                ('has_trypod', models.BooleanField(default=False)),
                ('has_flashgun', models.BooleanField(default=False)),
                ('has_ndfilter', models.BooleanField(default=False)),
                ('has_triger', models.BooleanField(default=False)),
                ('has_softbox', models.BooleanField(default=False)),
                ('skil_exp', models.CharField(blank=True, max_length=3000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
            options={
                'verbose_name_plural': 'DSLR_MirrorLess',
            },
        ),
        migrations.CreateModel(
            name='Arial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_drons', models.CharField(blank=True, max_length=200)),
                ('is_registered', models.BooleanField(default=False)),
                ('skil_exp', models.CharField(blank=True, max_length=3000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
            options={
                'verbose_name_plural': 'Arial',
            },
        ),
        migrations.CreateModel(
            name='Announcer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skil_exp', models.CharField(max_length=2000)),
                ('sinhala_lan', models.BooleanField(default=False)),
                ('english_lan', models.BooleanField(default=False)),
                ('tamil_lan', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory', models.ImageField(blank=True, upload_to='media/accessories/')),
                ('filed', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.fields')),
                ('member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
            options={
                'verbose_name_plural': 'Accessories',
            },
        ),
    ]
