# Generated by Django 4.1 on 2022-09-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gender_authentication_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='accessory',
            field=models.ImageField(blank=True, upload_to='accessories/'),
        ),
        migrations.AlterField(
            model_name='authentication_info',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member', unique=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member', unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile',
            field=models.ImageField(blank=True, default='profiles/default_user.png', upload_to='profiles/'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('just_member', models.BooleanField(default=False)),
                ('president_in_chief', models.BooleanField(default=False)),
                ('vice_president_in_chief', models.BooleanField(default=False)),
                ('Photography_president', models.BooleanField(default=False)),
                ('Photography_vice_president', models.BooleanField(default=False)),
                ('videography_president', models.BooleanField(default=False)),
                ('videography_vice_president', models.BooleanField(default=False)),
                ('technical_president', models.BooleanField(default=False)),
                ('technical_vice_president', models.BooleanField(default=False)),
                ('announcing_president', models.BooleanField(default=False)),
                ('announcing_vice_president', models.BooleanField(default=False)),
                ('reporting_president', models.BooleanField(default=False)),
                ('reporting_vice_president', models.BooleanField(default=False)),
                ('photo_and_video_editing_president', models.BooleanField(default=False)),
                ('photo_and_video_editing_vice_president', models.BooleanField(default=False)),
                ('graphic_designing_president', models.BooleanField(default=False)),
                ('graphic_designing_vice_president', models.BooleanField(default=False)),
                ('web_designing_president', models.BooleanField(default=False)),
                ('web_designing_vice_president', models.BooleanField(default=False)),
                ('promoted', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
    ]
