# Generated by Django 4.1.1 on 2022-09-26 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_accessory_accessory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='filed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fields'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member'),
        ),
        migrations.AlterField(
            model_name='authentication_info',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member'),
        ),
        migrations.CreateModel(
            name='Behaviour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviour_data', models.CharField(max_length=1000)),
                ('is_good', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
            options={
                'verbose_name_plural': 'Behaviour',
            },
        ),
    ]
