# Generated by Django 4.1.1 on 2022-09-26 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_accessory_filed_alter_accessory_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
