# Generated by Django 4.1.1 on 2022-10-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_member_gender_delete_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='parent_adress',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='member',
            name='parent_name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='parent_phone',
            field=models.CharField(default='null', max_length=12),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
