# Generated by Django 4.1.1 on 2022-10-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_member_parent_adress_member_parent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='parent_adress',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='member',
            name='parent_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='parent_phone',
            field=models.CharField(max_length=12),
        ),
    ]
