# Generated by Django 4.1.1 on 2022-10-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_member_parent_adress_alter_member_parent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='parent_adress',
        ),
        migrations.RemoveField(
            model_name='member',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='parent_phone',
        ),
    ]
