# Generated by Django 4.1.1 on 2022-10-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_member_parent_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='parent_adress',
            field=models.CharField(default='n', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='parent_name',
            field=models.CharField(default='n', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='parent_phone',
            field=models.CharField(default='n', max_length=12),
        ),
    ]
