# Generated by Django 4.1.1 on 2022-10-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_member_parent_adress_member_parent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
