# Generated by Django 4.1.1 on 2022-10-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_member_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
